PRIMARY_TAGS = {
    "isnad": "Die Übertragungskette von Personen, die zur eigentlichen Aussage (Hadith hadith) führt.",
    "hadith": "Der eigentliche Wortlaut oder Haupttext einer überlieferten Aussage (Hadith), abzüglich der Übertragungskette.",
    "source": "Die explizite Nennung eines Werkes bzw. Primärquellen-Gebers (z. B. 'Überliefert bei Buchari').",
    "quran_verse": "Direktes Zitat aus dem Koran im arabischen Originalwortlaut.",
}

SECONDARY_TAGS = {
    "command_and_prohibition": "Textstellen, die explizite Gebote (Amr) oder Verbote (Nahy) aus dem Vers ableiten.",
    "chain_evaluation": "Fachliche Bewertung der Qualität einer Überlieferungskette (z. B. Sahih, Da'if, Hassan).",
    "narrator_criticism": "Detaillierte Analyse oder Kritik einzelner Personen innerhalb einer Übertragungskette (Ilm al-Rijal).",
    "asbab_al_nuzul": "Berichte über den spezifischen historischen Anlass oder den Kontext der Offenbarung eines Verses.",
    "hadith_support": "Einbeziehung prophetischer Überlieferungen zur Untermauerung der Exegese.",
    "opinions_of_scholars": "Zusammenfassung oder direktes Zitat von Deutungen klassischer Exegeten (Tafsir-Gelehrte).",
}

REMAINING_ALL_TAGS = {
    "linguistic_analysis": "Untersuchung von Wortbedeutungen, Morphologie oder allgemeiner Sprachverwendung.",
    "qiraat": "Hinweise auf verschiedene anerkannte Lesarten des Korantextes.",
    "cross_references": "Verweise auf andere Koranstellen, die den aktuellen Vers erläutern.",
    "fiqh_implications": "Ableitung von rechtlichen Bestimmungen und juristischen Regeln aus dem Vers.",
    "theological_points": "Glaubenslehre (Aqidah) betreffende Schlussfolgerungen oder dogmatische Fragen.",
    "historical_context": "Allgemeine historische Rahmenbedingungen zur Zeit der Offenbarung (nicht spezifisch Asbab al-Nuzul).",
    "balagha_analysis": "Analyse der rhetorischen Schönheit, Eloquenz und Stilistik (Rhetorik).",
    "nasikh_wa_mansukh": "Diskussion über abrogierende (aufhebende) und abrogierte Verse.",
    "grammatical_parsing": "Syntax-Analyse (I'rab) und grammatikalische Zerlegung der Sätze.",
    "etymology": "Untersuchung des Ursprungs und der historischen Entwicklung einzelner Wörter.",
    "parabolic_meaning": "Deutung von Gleichnissen, Metaphern und allegorischen Darstellungen.",
    "sectarian_perspective": "Interpretation aus Sicht einer spezifischen theologischen Schule (z. B. Mu'tazila, Schia).",
    "spiritual_lessons": "Ethische, moralische oder sufisch-spirituelle Einsichten für das Seelenleben.",
    "biographies_of_narrators": "Biografische Informationen über die in der Isnad genannten Personen.",
    "ijma_status": "Feststellung eines Konsenses unter den Gelehrten zu einer bestimmten Auslegung.",
    "reason_for_revelation_variants": "Diskussion über unterschiedliche Berichte zum Offenbarungsanlass.",
    "legal_maxims": "Anwendung allgemeiner Rechtsgrundsätze (Qawa'id Fiqhiyya).",
    "maqasid_al_sharia": "Einordnung des Verses in die übergeordneten Ziele des islamischen Rechts.",
    "variant_interpretations": "Gegenüberstellung verschiedener, sich teils widersprechender Deutungsmöglichkeiten.",
    "minority_opinions": "Kennzeichnung von Auslegungen, die nur von einer Minderheit vertreten werden.",
    "majority_opinions": "Kennzeichnung der von der Mehrheit der Gelehrten (Jumhur) vertretenen Ansicht.",
    "literal_interpretation": "Auslegung basierend auf der rein äußerlichen, wortwörtlichen Bedeutung (Zahir).",
    "metaphorical_interpretation": "Auslegung, die eine übertragene, bildliche Bedeutung (Ta'wil) annimmt.",
    "contextual_scope": "Bestimmung des Geltungsbereichs eines Verses basierend auf dem Kontext.",
    "general_vs_specific": "Unterscheidung, ob eine Aussage allgemein ('Amm) oder spezifisch (Khass) gemeint ist.",
    "absolute_vs_restricted": "Unterscheidung zwischen uneingeschränkten (Mutlaq) und bedingten (Muqayyad) Aussagen.",
    "rhetorical_devices": "Identifikation spezifischer rhetorischer Figuren (z. B. Metonymie, Ironie).",
    "semantic_fields": "Analyse von Wortgruppen, die einen gemeinsamen Bedeutungsraum abdecken.",
    "synonym_analysis_homonym_antonym_analysis": "Vergleich von sinnverwandten, gleichlautenden oder gegensätzlichen Begriffen.",
    "chronological_order": "Einordnung des Verses in die zeitliche Abfolge der Offenbarung.",
    "meccan_medinan": "Klassifizierung, ob ein Vers in Mekka oder Medina offenbart wurde.",
    "intertextual_links": "Bezüge zu anderen religiösen Texten oder literarischen Werken.",
    "israiliyyat": "Hinweise auf Erzählungen biblischen Ursprungs oder jüdisch-christlicher Tradition.",
    "philosophical_reflections": "Abstrakte philosophische Überlegungen, die über die reine Exegese hinausgehen.",
    "ethical_implications": "Direkte Ableitung moralischer Verhaltensregeln für das Individuum.",
    "creedal_implications": "Spezifische Auswirkungen auf das Glaubensbekenntnis.",
    "aqidah_classification": "Systematische Zuordnung zu Kategorien der Glaubenslehre.",
    "scientific_allusions": "Interpretation von Versen in Bezug auf naturwissenschaftliche Erkenntnisse.",
    "cosmological_notes": "Anmerkungen zur Struktur des Universums, Himmel und Erde.",
    "social_norms": "Bezug auf gesellschaftliche Gepflogenheiten und soziale Strukturen.",
    "political_implications": "Bezüge zu Herrschaft, Staatswesen und politischer Ordnung.",
    "pedagogical_lessons": "Erziehungswissenschaftliche oder didaktische Rückschlüsse.",
    "daawah_applications": "Relevanz des Verses für die Glaubensverkündung und Mission.",
    "practical_guidance": "Konkrete Handlungsempfehlungen für den Alltag des Gläubigen.",
    "ritual_implications": "Auswirkungen auf die Durchführung gottesdienstlicher Handlungen (Ibadat).",
    "disputed_terms": "Analyse von Begriffen, deren Bedeutung unter Gelehrten stark umstritten ist.",
    "technical_definitions": "Definition von Fachbegriffen innerhalb der islamischen Wissenschaften.",
    "textual_variants": "Untersuchung von Abweichungen in verschiedenen Manuskripten oder Kodizes.",
    "manuscript_evidence": "Verweise auf physische Beweise in alten Koranhandschriften.",
    "comparative_tafsir": "Methodischer Vergleich zwischen verschiedenen Tafsir-Werken.",
    "methodological_notes": "Anmerkungen des Exegeten zu seiner eigenen methodischen Vorgehensweise.",
    "argument": "Logische Beweisführung oder dialektische Argumentation zur Stützung einer These.",
    "summary": "Kurze Zusammenfassung eines längeren Abschnitts oder einer Argumentationskette.",
    "conclusion": "Abschließendes Urteil oder Fazit am Ende einer Analyse.",
}
