list_of_lists_with_strings = [
    [
        "|<tafsir_chunk>\n",
        "<fiqh_implications>\n",
        "<variant_interpretations>\n",
        "<argument>\n",
        "<opinions_of_scholars>وقال آخرون : لا يجوز أكل الصيد للمحرم بالكلية ، ومنعوا من ذلك مطلقا ; لعموم هذه الآية الكريمة .</opinions_of_scholars>\n",
        "<opinions_of_scholars> وقال </opinions_of_scholars>\n",
        "<source/>عبد الرزاق\n",
        "            <opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن معمر</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن ابن طاوس</isnad>\n",
        "<opinions_of_scholars> و</opinions_of_scholars>\n",
        "<isnad>عبد الكريم بن أبي أمية</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن طاوس</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن ابن عباس</isnad>\n",
        "<opinions_of_scholars> ; أنه كره أكل لحم الصيد للمحرم .</opinions_of_scholars>\n",
        "<opinions_of_scholars> وقال : هي مبهمة .</opinions_of_scholars>\n",
        "<opinions_of_scholars> يعني قوله : </opinions_of_scholars>\n",
        "<quran_verse>( وحرم عليكم صيد البر ما دمتم حرما )</quran_verse>\n",
        "<opinions_of_scholars> .</opinions_of_scholars>\n",
        "<opinions_of_scholars> قال : وأخبرني </opinions_of_scholars>\n",
        "<isnad>معمر</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن الزهري</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن ابن عمر</isnad>\n",
        "<opinions_of_scholars> ; أنه كان يكره للمحرم أن يأكل من لحم الصيد على كل حال .</opinions_of_scholars>\n",
        "<opinions_of_scholars> قال </opinions_of_scholars>\n",
        "<isnad>معمر</isnad>\n",
        "<opinions_of_scholars> : وأخبرني </opinions_of_scholars>\n",
        "<isnad>أيوب</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن نافع</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن ابن عمر</isnad>\n",
        "<opinions_of_scholars> ، مثله .</opinions_of_scholars>\n",
        "<opinions_of_scholars> قال </opinions_of_scholars>\n",
        "<source/>ابن عبد البر\n",
        "            <opinions_of_scholars> : وبه قال </opinions_of_scholars>\n",
        "<source/>طاوس\n",
        "            <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>جابر بن زيد\n",
        "            <opinions_of_scholars> ، وإليه ذهب </opinions_of_scholars>\n",
        "<source/>الثوري\n",
        "            <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>إسحاق ابن راهويه\n",
        "            <opinions_of_scholars> - في رواية - وقد روي نحوه عن </opinions_of_scholars>\n",
        "<source/>علي بن أبي طالب\n",
        "            <opinions_of_scholars> ، رواه </opinions_of_scholars>\n",
        "<source/>ابن جرير\n",
        "            <opinions_of_scholars> من طريق </opinions_of_scholars>\n",
        "<isnad>سعيد بن أبي عروبة</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن قتادة</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن سعيد بن المسيب</isnad>\n",
        "<opinions_of_scholars> : أن </opinions_of_scholars>\n",
        "<source/>عليا\n",
        "            <opinions_of_scholars> كره لحم الصيد للمحرم على كل حال .</opinions_of_scholars>\n",
        "</argument>\n",
        "</variant_interpretations>\n",
        "</fiqh_implications>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "|<tafsir_chunk>\n",
        "<fiqh_implications>\n",
        "<variant_interpretations>\n",
        "<argument>\n",
        "<hadith_support>\n",
        "<opinions_of_scholars>وقد ورد حديث بنحو ذلك ، فقال </opinions_of_scholars>\n",
        "<source/>ابن مردويه\n",
        "              <opinions_of_scholars> : </opinions_of_scholars>\n",
        "<isnad>حدثنا عبد الباقي</isnad>\n",
        "<opinions_of_scholars> - هو </opinions_of_scholars>\n",
        "<isnad>ابن قانع</isnad>\n",
        "<opinions_of_scholars> - </opinions_of_scholars>\n",
        "<isnad>حدثنا الحسين بن إسحاق التستري</isnad>\n",
        "<opinions_of_scholars> و</opinions_of_scholars>\n",
        "<isnad>عبد الله بن موسى بن أبي عثمان</isnad>\n",
        "<opinions_of_scholars> قالا : </opinions_of_scholars>\n",
        "<isnad>حدثنا الحسين بن زيد الطحان</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>حدثنا حفص بن غياث</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن ابن أبي ذئب</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن أبي الزبير</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن جابر</isnad>\n",
        "<opinions_of_scholars> قال : قال رسول الله صلى الله عليه وسلم : </opinions_of_scholars>\n",
        '<hadith>" ما صدتموه وهو حي فمات فكلوه ، وما ألقى البحر ميتا طافيا فلا تأكلوه "</hadith>\n',
        "<opinions_of_scholars> .</opinions_of_scholars>\n",
        "<opinions_of_scholars> ثم رواه من طريق </opinions_of_scholars>\n",
        "<isnad>إسماعيل بن أمية</isnad>\n",
        "<opinions_of_scholars> و</opinions_of_scholars>\n",
        "<isnad>يحيى بن أبي أنيسة</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن أبي الزبير</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن جابر</isnad>\n",
        "<opinions_of_scholars> به .</opinions_of_scholars>\n",
        "<chain_evaluation>وهو منكر .</chain_evaluation>\n",
        "</hadith_support>\n",
        "</argument>\n",
        "</variant_interpretations>\n",
        "</fiqh_implications>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "|<tafsir_chunk>\n",
        "<fiqh_implications>\n",
        "<hadith_support>\n",
        "<argument>\n",
        "<opinions_of_scholars>وقال </opinions_of_scholars>\n",
        "<source/>الإمام أحمد\n",
        "            <opinions_of_scholars> : </opinions_of_scholars>\n",
        "<isnad>حدثنا سعيد بن منصور</isnad>\n",
        "<opinions_of_scholars> و</opinions_of_scholars>\n",
        "<isnad>قتيبة بن سعيد</isnad>\n",
        "<opinions_of_scholars> قالا </opinions_of_scholars>\n",
        "<isnad>حدثنا يعقوب بن عبد الرحمن</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن عمرو بن أبي عمرو</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن المطلب بن عبد الله بن حنطب</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن جابر بن عبد الله</isnad>\n",
        "<opinions_of_scholars> قال : قال رسول الله - - صلى الله عليه وسلم - - وقال </opinions_of_scholars>\n",
        "<isnad>قتيبة</isnad>\n",
        "<opinions_of_scholars> في حديثه : سمعت رسول الله - صلى الله عليه وسلم - - يقول : </opinions_of_scholars>\n",
        '<hadith>" صيد البر لكم حلال - قال سعيد : وأنتم حرم - ما لم تصيدوه أو يصد لكم "</hadith>\n',
        "<opinions_of_scholars> .</opinions_of_scholars>\n",
        "<opinions_of_scholars> وكذا رواه </opinions_of_scholars>\n",
        "<source/>أبو داود\n",
        "            <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>الترمذي\n",
        "            <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>النسائي\n",
        "            <opinions_of_scholars> جميعا ، عن </opinions_of_scholars>\n",
        "<source/>قتيبة\n",
        "            <opinions_of_scholars> .</opinions_of_scholars>\n",
        "<opinions_of_scholars> وقال </opinions_of_scholars>\n",
        "<source/>الترمذي\n",
        "            <opinions_of_scholars> : </opinions_of_scholars>\n",
        "<chain_evaluation>لا نعرف للمطلب سماعا من جابر .</chain_evaluation>\n",
        "<opinions_of_scholars> ورواه </opinions_of_scholars>\n",
        "<source/>الإمام محمد بن إدريس الشافعي\n",
        "            <opinions_of_scholars> ، من طريق </opinions_of_scholars>\n",
        "<isnad>عمرو بن أبي عمرو</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن مولاه المطلب</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن جابر</isnad>\n",
        "<opinions_of_scholars> ثم قال : وهذا أحسن حديث روي في هذا الباب وأقيس .</opinions_of_scholars>\n",
        "</argument>\n",
        "</hadith_support>\n",
        "</fiqh_implications>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "|<tafsir_chunk>\n",
        "<asbab_al_nuzul>\n",
        "<opinions_of_scholars>\n",
        "<isnad>وقال أسباط ، عن السدي</isnad>\n",
        "</opinions_of_scholars>\n",
        "                في قوله :\n",
        "                <quran_verse>( يا أيها الذين آمنوا لا تحرموا طيبات ما أحل الله لكم ولا تعتدوا إن الله لا يحب المعتدين )</quran_verse>\n",
        "                وذلك أن رسول الله صلى الله عليه وسلم جلس يوما فذكر الناس ، ثم قام ولم يزدهم على التخويف ، فقال ناس من أصحاب النبي صلى الله عليه وسلم ، كانوا عشرة منهم\n",
        "                <isnad>علي بن أبي طالب</isnad>\n",
        "                و\n",
        "                <isnad>عثمان بن مظعون</isnad>\n",
        "                : ما خفنا إن لم نحدث عملا فإن النصارى قد حرموا على أنفسهم ، فنحن نحرم . فحرم بعضهم أن يأكل اللحم والودك ، وأن يأكل بنهار ، وحرم بعضهم النوم ، وحرم بعضهم النساء ، فكان\n",
        "                <isnad>عثمان بن مظعون</isnad>\n",
        "                ممن حرم النساء وكان لا يدنو من أهله ولا تدنو منه . فأتت امرأته\n",
        "                <isnad>عائشة رضي الله عنها</isnad>\n",
        "                ، وكان يقال لها : الحولاء فقالت لها\n",
        "                <isnad>عائشة</isnad>\n",
        '                ومن عندها من أزواج النبي صلى الله عليه وسلم : ما بالك يا حولاء متغيرة اللون ، لا تمتشطين ، لا تتطيبين؟ قالت : وكيف أمتشط وأتطيب وما وقع علي زوجي وما رفع عني ثوبا ، منذ كذا وكذا . قال : فجعلن يضحكن من كلامها ، فدخل رسول الله صلى الله عليه وسلم وهن يضحكن ، فقال : " ما يضحككن؟ " قالت : يا رسول الله ، إن الحولاء سألتها عن أمرها ، فقالت : ما رفع عني زوجي ثوبا منذ كذا وكذا . فأرسل إليه فدعاه ، فقال : " ما لك يا عثمان ؟ " قال : إني تركته لله ، لكي أتخلى للعبادة ، وقص عليه أمره ، وكان\n',
        "                <isnad>عثمان</isnad>\n",
        '                قد أراد أن يجب نفسه ، فقال رسول الله صلى الله عليه وسلم : " أقسمت عليك إلا رجعت فواقعت أهلك " . فقال : يا رسول الله ، إني صائم . فقال : " أفطر " . فأفطر ، وأتى أهله ، فرجعت الحولاء إلى\n',
        "                <isnad>عائشة [ زوج رسول الله صلى الله عليه وسلم ]</isnad>\n",
        "                وقد امتشطت واكتحلت وتطيبت ، فضحكت\n",
        "                <isnad>عائشة</isnad>\n",
        "                وقالت : ما لك يا حولاء؟ فقالت : إنه أتاها أمس ،\n",
        "                <hadith_support>\n",
        '<hadith>وقال رسول الله صلى الله عليه وسلم : " ما بال أقوام حرموا النساء والطعام والنوم؟ ألا إني أنام وأقوم ، وأفطر وأصوم ، وأنكح النساء ، فمن رغب عني فليس مني " .</hadith>\n',
        "</hadith_support>\n",
        "                فنزلت :\n",
        "                <quran_verse>( ياأيها الذين آمنوا لا تحرموا طيبات ما أحل الله لكم ولا تعتدوا )</quran_verse>\n",
        "                يقول\n",
        "                <opinions_of_scholars>لعثمان</opinions_of_scholars>\n",
        '                " لا تجب نفسك ، فإن هذا هو الاعتداء " . وأمرهم أن يكفروا عن أيمانهم ، فقال :\n',
        "                <quran_verse>( لا يؤاخذكم الله باللغو في أيمانكم ولكن يؤاخذكم بما عقدتم الأيمان )</quran_verse>\n",
        "</asbab_al_nuzul>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "4144|<tafsir_chunk>\n",
        "<asbab_al_nuzul>\n",
        "        وقد ذكر <source/>ابن جرير ، رحمه الله ، أن هذه الآية نزلت في شأن ثابت بن قيس بن شماس وامرأته حبيبة بنت عبد الله بن أبي ابن سلول . ولنذكر طرق حديثها ، واختلاف ألفاظه :\n",
        "      </asbab_al_nuzul>\n",
        "<asbab_al_nuzul>\n",
        '<source/>قال الإمام مالك في موطئه : <isnad>عن يحيى بن سعيد ، عن عمرة بنت عبد الرحمن بن سعد بن زرارة ، أنها أخبرته عن حبيبة بنت سهل الأنصارية</isnad> ، <hadith>أنها كانت تحت ثابت بن قيس بن شماس ، وأن رسول الله صلى الله عليه وسلم خرج إلى الصبح فوجد حبيبة بنت سهل عند بابه في الغلس ، فقال رسول الله صلى الله عليه وسلم : " من هذه ؟ " قالت : أنا حبيبة بنت سهل . فقال : " ما شأنك ؟ " فقالت : لا أنا ولا ثابت بن قيس لزوجها فلما جاء زوجها ثابت بن قيس قال له رسول الله صلى الله عليه وسلم : " هذه حبيبة بنت سهل قد ذكرت ما شاء الله أن تذكر " . فقالت حبيبة : يا رسول الله ، كل ما أعطاني عندي . فقال رسول الله صلى الله عليه وسلم : " خذ منها " . فأخذ منها وجلست في أهلها .</hadith>\n',
        "</asbab_al_nuzul>\n",
        "<asbab_al_nuzul>\n",
        "<source/>وهكذا رواه الإمام أحمد ، <isnad>عن عبد الرحمن بن مهدي ، عن مالك بإسناده مثله</isnad> . <source/>ورواه أبو داود ، <isnad>عن القعنبي ، عن مالك</isnad> . <source/>والنسائي ، <isnad>عن محمد بن مسلمة ، عن ابن القاسم ، عن مالك به</isnad> .\n",
        "      </asbab_al_nuzul>\n",
        "<asbab_al_nuzul>\n",
        '        حديث آخر : عن عائشة : <source/>قال أبو داود وابن جرير : <isnad>حدثنا محمد بن معمر ، حدثنا أبو عامر ، حدثنا أبو عمرو السدوسي ، عن عبد الله بن أبي بكر عن عمرة ، عن عائشة</isnad> ، <hadith>أن حبيبة بنت سهل كانت تحت ثابت بن قيس بن شماس ، فضربها فكسر نغضها فأتت رسول الله صلى الله عليه وسلم بعد الصبح فاشتكته إليه ، فدعا رسول الله صلى الله عليه وسلم ثابتا فقال : " خذ بعض مالها وفارقها " . قال : ويصلح ذلك يا رسول الله ؟ قال : " نعم " . قال : فإني أصدقتها حديقتين ، فهما بيدها . فقال النبي صلى الله عليه وسلم : " خذهما وفارقها " . ففعل .</hadith> وهذا لفظ <source/>ابن جرير . وأبو عمرو السدوسي هو سعيد بن سلمة بن أبي الحسام .\n',
        "      </asbab_al_nuzul>\n",
        "<asbab_al_nuzul>\n",
        '        حديث آخر فيه : عن ابن عباس رضي الله عنه : <source/>قال البخاري : <isnad>حدثنا أزهر بن جميل ، أخبرنا عبد الوهاب الثقفي ، حدثنا خالد ، عن عكرمة ، عن ابن عباس</isnad> : <hadith>أن امرأة ثابت بن قيس بن شماس أتت النبي صلى الله عليه وسلم ، فقالت : يا رسول الله ، ما أعتب عليه في خلق ولا دين ، ولكن أكره الكفر في الإسلام . فقال رسول الله صلى الله عليه وسلم : " أتردين عليه حديقته ؟ " قالت : نعم . قال رسول الله صلى الله عليه وسلم : " اقبل الحديقة وطلقها تطليقة " .</hadith> <source/>وكذا رواه النسائي ، <isnad>عن أزهر بن جميل بإسناده</isnad> ، مثله . <source/>ورواه البخاري أيضا ، <isnad>عن إسحاق الواسطي ، عن خالد هو ابن عبد الله الطحان ، عن خالد ، هو ابن مهران الحذاء ، عن عكرمة به</isnad> ، نحوه . <source/>وهكذا رواه البخاري أيضا من طرق ، <isnad>عن أيوب ، عن عكرمة ، عن ابن عباس</isnad> ، به . وفي بعضها أنها قالت : لا أطيقه ، تعني : بغضا . <chain_evaluation>وهذا الحديث من أفراد البخاري من هذا الوجه</chain_evaluation> .\n',
        "      </asbab_al_nuzul>\n",
        "<asbab_al_nuzul>\n",
        '        ثم قال : <isnad>حدثنا سليمان بن حرب ، حدثنا حماد بن زيد ، عن أيوب ، عن عكرمة ، أن جميلة رضي الله عنها</isnad> . كذا قال ، والمشهور أن اسمها حبيبة [ كما تقدم ] . <source/>قال الحافظ أبو بكر بن مردويه في تفسيره : <isnad>حدثنا موسى بن هارون ، حدثنا أزهر بن مروان الرقاشي ، حدثنا عبد الأعلى ، حدثنا سعيد ، عن قتادة ، عن عكرمة ، عن ابن عباس</isnad> ، <hadith>أن جميلة بنت سلول أتت النبي صلى الله عليه وسلم فقالت : والله ما أعتب على ثابت بن قيس بن شماس في دين ولا خلق ، ولكنني أكره الكفر بعد الإسلام ، لا أطيقه بغضا . فقال النبي صلى الله عليه وسلم : " تردين عليه حديقته ؟ " قالت : نعم ، فأمره رسول الله صلى الله عليه وسلم أن يأخذ منها حديقته ولا يزداد .</hadith> <source/>وهكذا رواه ابن ماجه <isnad>عن أزهر بن مروان ، بإسناده</isnad> مثله سواء ، <chain_evaluation>وهو إسناد جيد مستقيم</chain_evaluation> .\n',
        "      </asbab_al_nuzul>\n",
        "<asbab_al_nuzul>\n",
        '<source/>ورواه أيضا أبو القاسم البغوي ، <isnad>عن عبيد الله القواريري ، عن عبد الأعلى</isnad> ، مثله ، لكن <source/>قال ابن جرير : <isnad>حدثنا ابن حميد ، حدثنا يحيى بن واضح ، حدثنا الحسين بن واقد ، عن ثابت ، عن عبد الله بن رباح عن جميلة بنت أبي ابن سلول</isnad> : <hadith>أنها كانت تحت ثابت بن قيس ، فنشزت عليه ، فأرسل إليها النبي صلى الله عليه وسلم فقال : " يا جميلة ، ما كرهت من ثابت ؟ " قالت : والله ما كرهت منه دينا ولا خلقا ، إلا أني كرهت دمامته ! فقال لها : " أتردين الحديقة ؟ " قالت : نعم . فردت الحديقة ، وفرق بينهما .</hadith>\n',
        "</asbab_al_nuzul>\n",
        "<asbab_al_nuzul>\n",
        '<source/>قال ابن جرير أيضا : <isnad>حدثنا محمد بن عبد الأعلى ، حدثنا المعتمر بن سليمان قال : قرأت على فضيل ، عن أبي جرير أنه سأل عكرمة : هل كان للخلع أصل ؟ قال : كان ابن عباس يقول</isnad> : <hadith>إن أول خلع كان في الإسلام في أخت عبد الله بن أبي ، أنها أتت رسول الله صلى الله عليه وسلم ، فقالت : يا رسول الله ، لا يجمع رأسي ورأسه شيء أبدا ، إني رفعت جانب الخباء ، فرأيته أقبل في عدة ، فإذا هو أشدهم سوادا ، وأقصرهم قامة وأقبحهم وجها . قال زوجها : يا رسول الله ، إني قد أعطيتها أفضل مالي ، حديقة لي ، فإن ردت علي حديقتي ؟ قال : " ما تقولين ؟ " قالت : نعم ، وإن شاء زدته . قال : ففرق بينهما .</hadith>\n',
        "</asbab_al_nuzul>\n",
        "<asbab_al_nuzul>\n",
        '        حديث آخر : <source/>قال ابن ماجه : <isnad>حدثنا أبو كريب ، حدثنا أبو خالد الأحمر ، عن حجاج ، عن عمرو بن شعيب ، عن أبيه ، عن جده قال</isnad> : <hadith>كانت حبيبة بنت سهل تحت ثابت بن قيس بن شماس ، وكان رجلا دميما ، فقالت : يا رسول الله ، والله لولا مخافة الله إذا دخل علي بصقت في وجهه ! فقال رسول الله صلى الله عليه وسلم : " أتردين عليه حديقته ؟ " قالت : نعم . فردت عليه حديقته . قال ففرق بينهما رسول الله صلى الله عليه وسلم .</hadith>\n',
        "</asbab_al_nuzul>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "|<tafsir_chunk>\n",
        "<hadith_support>\n",
        "<opinions_of_scholars>وقال </opinions_of_scholars>\n",
        "<source/>ابن ماجه\n",
        "        <opinions_of_scholars> : </opinions_of_scholars>\n",
        "<isnad>حدثنا هارون بن عبد الله الحمال</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>حدثنا هاشم بن القاسم</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>حدثنا زياد بن عبد الله</isnad>\n",
        "<opinions_of_scholars> عن </opinions_of_scholars>\n",
        "<isnad>علاثة</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن موسى بن محمد بن إبراهيم</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن أبيه</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن جابر</isnad>\n",
        "<opinions_of_scholars> و</opinions_of_scholars>\n",
        "<isnad>أنس بن مالك</isnad>\n",
        "<opinions_of_scholars> أن النبي صلى الله عليه وسلم كان إذا دعا على الجراد قال : </opinions_of_scholars>\n",
        '<hadith>" اللهم أهلك كباره ، واقتل صغاره ، وأفسد بيضه ، واقطع دابره ، وخذ بأفواهه عن معايشنا وأرزاقنا ، إنك سميع الدعاء "</hadith>\n',
        "<opinions_of_scholars> .</opinions_of_scholars>\n",
        "<opinions_of_scholars> فقال </opinions_of_scholars>\n",
        "<source/>خالد\n",
        "        <opinions_of_scholars> : يا رسول الله ، كيف تدعو على جند من أجناد الله بقطع دابره؟</opinions_of_scholars>\n",
        "<opinions_of_scholars> فقال : </opinions_of_scholars>\n",
        '<hadith>" إن الجراد نثرة الحوت في البحر "</hadith>\n',
        "<opinions_of_scholars> .</opinions_of_scholars>\n",
        "<opinions_of_scholars> قال </opinions_of_scholars>\n",
        "<source/>هاشم\n",
        "        <opinions_of_scholars> : قال </opinions_of_scholars>\n",
        "<source/>زياد\n",
        "        <opinions_of_scholars> : فحدثني من رأى الحوت ينثره .</opinions_of_scholars>\n",
        "<chain_evaluation>تفرد به </chain_evaluation>\n",
        "<source/>ابن ماجه\n",
        "        <chain_evaluation> .</chain_evaluation>\n",
        "</hadith_support>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "5210|<tafsir_chunk>\n",
        "<methodological_notes>\n",
        "        هكذا وقع هذا الحديث في مسند <source/>الإمام أحمد ، رحمه الله ، من رواية <isnad>ابن أبي مليكة ، عن عائشة</isnad> ، ليس بينهما أحد . \n",
        "        وهكذا رواه <source/>ابن ماجه من طريق <isnad>إسماعيل ابن علية وعبد الوهاب الثقفي ، كلاهما عن أيوب ، عن عبد الله بن عبيد الله بن أبي مليكة ، عنها</isnad> . \n",
        "        ورواه <source/>محمد بن يحيى العبدي في مسنده عن <isnad>عبد الوهاب الثقفي ، عن أيوب ، به</isnad> . \n",
        "        وكذا رواه <source/>عبد الرزاق ، عن معمر عن أيوب . وكذا رواه غير واحد عن أيوب . وقد رواه <source/>ابن حبان في صحيحه ، من حديث أيوب ، به . \n",
        "        وتابع أيوب <isnad>أبو عامر الخزاز وغيره عن ابن أبي مليكة</isnad> ، فرواه <source/>الترمذي عن <isnad>بندار ، عن أبي داود الطيالسي ، عن أبي عامر الخزاز</isnad> ، فذكره . \n",
        "        وهكذا رواه <source/>سعيد بن منصور في سننه ، عن <isnad>حماد بن يحيى الأبح ، عن عبد الله بن أبي مليكة ، عن عائشة</isnad> . \n",
        "        ورواه <source/>ابن جرير ، من حديث <isnad>روح بن القاسم ونافع بن عمر الجمحي ، كلاهما عن ابن أبي مليكة ، عن عائشة</isnad> ، به . \n",
        "        وقال <isnad>نافع</isnad> في روايته عن ابن أبي مليكة : حدثتني عائشة ، فذكره .\n",
        "      </methodological_notes>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "6425|<tafsir_chunk>\n",
        "<hadith_support>\n",
        "        وقال\n",
        "        <source/>الإمام أحمد\n",
        "        : حدثنا\n",
        "        <isnad>سليمان بن داود أخبرنا عبد الرحمن بن أبي الزناد ، عن أبيه ، عن عبيد الله عن ابن عباس</isnad>\n",
        "        أنه قال :\n",
        "        <hadith>ما نصر الله في موطن كما نصره يوم أحد .</hadith>\n",
        "        قال : فأنكرنا ذلك ، فقال\n",
        "        <isnad>ابن عباس</isnad>\n",
        "        : بيني وبين من أنكر ذلك كتاب الله ، إن الله يقول في يوم أحد :\n",
        "        <quran_verse>( ولقد صدقكم الله وعده إذ تحسونهم بإذنه )</quran_verse>\n",
        "        يقول\n",
        "        <isnad>ابن عباس</isnad>\n",
        "        :\n",
        "        <linguistic_analysis>والحس : القتل</linguistic_analysis>\n",
        "<quran_verse>( حتى إذا فشلتم وتنازعتم في الأمر وعصيتم من بعد ما أراكم ما تحبون منكم من يريد الدنيا ومنكم من يريد الآخرة )</quran_verse>\n",
        "        الآية وإنما عنى بهذا الرماة ، وذلك أن النبي صلى الله عليه وسلم أقامهم في موضع ، ثم قال :\n",
        '        <hadith>" احموا ظهورنا ، فإن رأيتمونا نقتل فلا تنصرونا وإن رأيتمونا قد غنمنا فلا تشركونا . "</hadith>\n',
        "        فلما غنم النبي صلى الله عليه وسلم وأباحوا عسكر المشركين أكبت الرماة جميعا [ ودخلوا ] في العسكر ينهبون ، ولقد التقت صفوف أصحاب رسول الله صلى الله عليه وسلم ، فهم هكذا - وشبك بين يديه - وانتشبوا ، فلما أخل الرماة تلك الخلة التي كانوا فيها ، دخلت الخيل من ذلك الموضع على أصحاب رسول الله صلى الله عليه وسلم ، فضرب بعضهم بعضا والتبسوا ، وقتل من المسلمين ناس كثير ، وقد كان لرسول الله صلى الله عليه وسلم وأصحابه أول النهار ، حتى قتل من أصحاب لواء المشركين سبعة أو تسعة ، وجال المسلمون جولة نحو الجبل ولم يبلغوا - حيث يقول الناس - الغار ، إنما كان تحت المهراس ، وصاح الشيطان : قتل محمد ، فلم يشك فيه أنه حق ، فما زلنا كذلك ما نشك أنه حق ، حتى طلع رسول الله صلى الله عليه وسلم بين السعدين ، نعرفه بتلفته إذا مشى - قال : ففرحنا حتى كأنه لم يصبنا ما أصابنا - قال : فرقي نحونا وهو يقول :\n",
        '        <hadith>" اشتد غضب الله على قوم دموا وجه رسول الله "</hadith>\n',
        "        . ويقول مرة أخرى :\n",
        '        <hadith>" اللهم إنه ليس لهم أن يعلونا "</hadith>\n',
        "        . حتى انتهى إلينا ، فمكث ساعة ، فإذا أبو سفيان يصيح في أسفل الجبل : اعل هبل ، مرتين - يعني آلهته - أين ابن أبي كبشة ؟ أين ابن أبي قحافة ؟ أين ابن الخطاب ؟ فقال\n",
        "        <isnad>عمر</isnad>\n",
        "        : يا رسول الله ، ألا أجيبه ؟ قال :\n",
        '        <hadith>" بلى "</hadith>\n',
        "        قال : فلما قال : اعل هبل . قال\n",
        "        <isnad>عمر</isnad>\n",
        "        : الله أعلى وأجل . فقال أبو سفيان : قد أنعمت عينها فعاد عنها أو : فعال ! فقال : أين ابن أبي كبشة ؟ أين ابن أبي قحافة ؟ أين ابن الخطاب ؟ فقال\n",
        "        <isnad>عمر</isnad>\n",
        "        : هذا رسول الله ، وهذا أبو بكر ، وها أنا ذا عمر . قال : فقال أبو سفيان : يوم بيوم بدر ، الأيام دول ، وإن الحرب سجال . قال : فقال\n",
        "        <isnad>عمر</isnad>\n",
        "        : لا سواء ، قتلانا في الجنة وقتلاكم في النار . قال إنكم تزعمون ذلك ، لقد خبنا إذا وخسرنا ، ثم قال أبو سفيان : إنكم ستجدون في قتلاكم مثلة ولم يكن ذلك على رأي سراتنا . قال : ثم أدركته حمية الجاهلية فقال : أما إنه إن كان ذلك لم نكرهه .\n",
        "      </hadith_support>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "6430|<tafsir_chunk>\n",
        "<hadith_support>\n",
        "        وقال\n",
        "        <source/>محمد بن إسحاق\n",
        "        : حدثني\n",
        "        <isnad>يحيى بن عباد بن عبد الله بن الزبير ، عن أبيه ، عن جده أن الزبير بن العوام</isnad>\n",
        "        قال : والله لقد رأيتني أنظر إلى خدم [ هند ] وصواحباتها مشمرات هوارب ما دون أخذهن كثير ولا قليل ومالت الرماة إلى العسكر حين كشفنا القوم عنه ، يريدون النهب وخلوا ظهورنا للخيل فأتتنا من أدبارنا ، وصرخ صارخ : ألا إن محمدا قد قتل . فانكفأنا وانكفأ علينا القوم بعد أن أصبنا أصحاب اللواء ، حتى ما يدنو منه أحد من القوم . قال\n",
        "        <isnad>محمد بن إسحاق</isnad>\n",
        "        : فلم يزل لواء المشركين صريعا ، حتى أخذته عمرة بنت علقمة الحارثية ، فدفعته لقريش فلاثوا به ،\n",
        "      </hadith_support>\n",
        "      وقال\n",
        "      <source/>السدي\n",
        "      عن\n",
        "      <isnad>عبد خير</isnad>\n",
        "      قال : قال\n",
        "      <isnad>عبد الله بن مسعود</isnad>\n",
        "      قال : ما كنت أرى أن أحدا من أصحاب رسول الله صلى الله عليه وسلم يريد الدنيا حتى نزلت فينا ما نزل يوم أحد\n",
        "      <quran_verse>( منكم من يريد الدنيا ومنكم من يريد الآخرة )</quran_verse>\n",
        "      وقد روي من غير وجه عن\n",
        "      <isnad>ابن مسعود</isnad>\n",
        "      ، وكذا روي عن\n",
        "      <isnad>عبد الرحمن بن عوف</isnad>\n",
        "      و\n",
        "      <isnad>أبي طلحة</isnad>\n",
        "      ، رواهن\n",
        "      <source/>ابن مردويه\n",
        "      في تفسيره .\n",
        "    </tafsir_chunk>\n",
    ],
    [
        "|<tafsir_chunk>\n",
        "<hadith_support>\n",
        '<source/>وهكذا رواه أيضا في " كتاب التوحيد "\n',
        "\t\t\t\t<isnad> عن قتيبة ، عن حماد به</isnad>\n",
        "</hadith_support>\n",
        "<hadith_support>\n",
        '<source/>ورواه النسائي [ أيضا ] في " التفسير "\n',
        "\t\t\t\t<isnad> ، عن قتيبة ومحمد بن النضر بن مساور ويحيى بن حبيب بن عربي أربعتهم ، عن حماد بن زيد ، به .</isnad>\n",
        "</hadith_support>\n",
        "<hadith_support>\n",
        "<source/>وقد رواه الحميدي في مسنده ،\n",
        "\t\t\t\t<isnad> عن سفيان بن عيينة ، عن عمرو بن دينار ، سمع جابرا عن النبي - صلى الله عليه وسلم - ، به .</isnad>\n",
        "</hadith_support>\n",
        "<hadith_support>\n",
        "<source/>ورواه ابن حبان في صحيحه ،\n",
        "\t\t\t\t<isnad> عن أبي يعلى الموصلي ، عن أبي خيثمة ، عن سفيان بن عيينة ، به .</isnad>\n",
        "</hadith_support>\n",
        "<hadith_support>\n",
        "<source/>ورواه ابن جرير في تفسيره\n",
        "\t\t\t\t<isnad> عن أحمد بن الوليد القرشي وسعيد بن الربيع وسفيان بن وكيع ، كلهم عن سفيان بن عيينة ، به .</isnad>\n",
        "</hadith_support>\n",
        "<hadith_support>\n",
        "<source/>ورواه أبو بكر بن مردويه ،\n",
        "\t\t\t\t<isnad> من حديث آدم بن أبي إياس ويحيى بن عبد الحميد وعاصم بن علي ، عن سفيان بن عيينة ، به .</isnad>\n",
        "</hadith_support>\n",
        "<hadith_support>\n",
        "<source/>ورواه سعيد بن منصور ،\n",
        "\t\t\t\t<isnad> عن حماد بن زيد وسفيان بن عيينة ، كلاهما عن عمرو بن دينار ، به</isnad>\n",
        "</hadith_support>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "|<tafsir_chunk>\n",
        "<fiqh_implications>\n",
        "<variant_interpretations>\n",
        "<opinions_of_scholars>وأما إذا صاد حلال صيدا فأهداه إلى محرم ، فقد ذهب ذاهبون إلى إباحته مطلقا ، ولم يستفصلوا بين أن يكون قد صاده لأجله أم لا .</opinions_of_scholars>\n",
        "<opinions_of_scholars> حكى هذا القول </opinions_of_scholars>\n",
        "<source/>أبو عمر بن عبد البر\n",
        "          <opinions_of_scholars> ، عن </opinions_of_scholars>\n",
        "<source/>عمر بن الخطاب\n",
        "          <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>أبي هريرة\n",
        "          <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>الزبير بن العوام\n",
        "          <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>كعب الأحبار\n",
        "          <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>مجاهد\n",
        "          <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>عطاء\n",
        "          <opinions_of_scholars> - في رواية - و</opinions_of_scholars>\n",
        "<source/>سعيد بن جبير\n",
        "          <opinions_of_scholars> .</opinions_of_scholars>\n",
        "<opinions_of_scholars> قال : وبه قال </opinions_of_scholars>\n",
        "<source/>الكوفيون\n",
        "          <opinions_of_scholars> .</opinions_of_scholars>\n",
        "<opinions_of_scholars> قال </opinions_of_scholars>\n",
        "<source/>ابن جرير\n",
        "          <opinions_of_scholars> : </opinions_of_scholars>\n",
        "<isnad>حدثنا محمد بن عبد الله بن بزيع</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>حدثنا بشر بن المفضل</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>حدثنا سعيد</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن قتادة</isnad>\n",
        "<opinions_of_scholars> ، أن </opinions_of_scholars>\n",
        "<isnad>سعيد بن المسيب</isnad>\n",
        "<opinions_of_scholars> حدثه ، </opinions_of_scholars>\n",
        "<isnad>عن أبي هريرة</isnad>\n",
        "<opinions_of_scholars> ; أنه سئل عن لحم صيد صاده حلال ، أيأكله المحرم؟</opinions_of_scholars>\n",
        "<opinions_of_scholars> قال : فأفتاهم بأكله .</opinions_of_scholars>\n",
        "<opinions_of_scholars> ثم لقي </opinions_of_scholars>\n",
        "<source/>عمر بن الخطاب\n",
        "          <opinions_of_scholars> فأخبره بما كان من أمره ، فقال : لو أفتيتهم بغير هذا لأوجعت لك رأسك .</opinions_of_scholars>\n",
        "</variant_interpretations>\n",
        "</fiqh_implications>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "2407|<tafsir_chunk>\n",
        "<source/>وقال الإمام أحمد : \n",
        "      <isnad>حدثنا موسى بن داود ، حدثنا فليح بن سليمان ، عن هلال بن علي ، عن عطاء بن يسار</isnad> ، قال : \n",
        "      <hadith>لقيت عبد الله بن عمرو بن العاص ، فقلت : أخبرني عن صفة رسول الله صلى الله عليه وسلم في التوراة . فقال : أجل ، والله إنه لموصوف في التوراة بصفته في القرآن : يا أيها النبي إنا أرسلناك شاهدا ومبشرا ونذيرا ، وحرزا للأميين ، وأنت عبدي ورسولي ، سميتك المتوكل ، لا فظ ولا غليظ ولا سخاب في الأسواق ، ولا يدفع بالسيئة السيئة ولكن يعفو ويغفر ، ولن يقبضه حتى يقيم به الملة العوجاء ، بأن يقولوا : لا إله إلا الله . فيفتح به أعينا عميا ، وآذانا صما ، وقلوبا غلفا .</hadith>\n",
        "<source/>انفرد بإخراجه البخاري ، فرواه في <source/>البيوع عن <isnad>محمد بن سنان ، عن فليح</isnad> ، به . \n",
        "      وقال : تابعه <isnad>عبد العزيز بن أبي سلمة ، عن هلال</isnad> . \n",
        "      وقال <source/>سعيد : عن <isnad>هلال ، عن عطاء ، عن عبد الله بن سلام</isnad> . \n",
        "      ورواه في <source/>التفسير عن <isnad>عبد الله ، عن عبد العزيز بن أبي سلمة ، عن هلال ، عن عطاء ، عن عبد الله بن عمرو بن العاص</isnad> ، به . فذكر نحوه ، فعبد الله هذا هو <source/>ابن صالح ، كما صرح به في كتاب الأدب . \n",
        "      <opinions_of_scholars>وزعم <source/>أبو مسعود الدمشقي أنه <source/>عبد الله بن رجاء .</opinions_of_scholars>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "2466|<tafsir_chunk>\n",
        "<hadith_support>\n",
        "        وقال <source/>الإمام أحمد : حدثنا <isnad>هشيم ، حدثنا حميد</isnad> ، عن <source/>أنس ، قال : قال <source/>عمر رضي الله عنه : <hadith>وافقت ربي عز وجل في ثلاث ، قلت : يا رسول الله ، لو اتخذنا من مقام إبراهيم مصلى ؟ فنزلت : ( <quran_verse>واتخذوا من مقام إبراهيم مصلى</quran_verse> ) وقلت : يا رسول الله ، إن نساءك يدخل عليهن البر والفاجر ، فلو أمرتهن أن يحتجبن ؟ فنزلت آية الحجاب . واجتمع على رسول الله صلى الله عليه وسلم نساؤه في الغيرة فقلت لهن : ( <quran_verse>عسى ربه إن طلقكن أن يبدله أزواجا خيرا منكن</quran_verse> ) [ التحريم : 5 ] فنزلت كذلك .</hadith> \n",
        "        ثم رواه <source/>أحمد ، عن <isnad>يحيى وابن أبي عدي ، كلاهما عن حميد ، عن أنس</isnad> ، عن <source/>عمر أنه قال : وافقت ربي في ثلاث ، أو وافقني ربي في ثلاث فذكره . \n",
        "        وقد رواه <source/>البخاري عن <source/>عمرو بن عون و <source/>الترمذي عن <source/>أحمد بن منيع ، و <source/>النسائي عن <source/>يعقوب بن إبراهيم الدورقي ، و <source/>ابن ماجه عن <source/>محمد بن الصباح ، كلهم عن <isnad>هشيم بن بشير</isnad> ، به . \n",
        "        ورواه <source/>الترمذي أيضا عن <isnad>عبد بن حميد ، عن حجاج بن منهال ، عن حماد بن سلمة</isnad> ، و <source/>النسائي عن <isnad>هناد ، عن يحيى بن أبي زائدة</isnad> ، كلاهما عن <source/>حميد ، وهو <source/>ابن تيرويه الطويل ، به . \n",
        "        <chain_evaluation>وقال <source/>الترمذي : حسن صحيح .</chain_evaluation>\n",
        "        ورواه <source/>الإمام علي بن المديني عن <isnad>يزيد بن زريع ، عن حميد</isnad> به . وقال : هذا من صحيح الحديث ، وهو بصري ، ورواه <source/>الإمام مسلم بن الحجاج في صحيحه بسند آخر ، ولفظ آخر ، فقال : حدثنا <isnad>عقبة بن مكرم ، أخبرنا سعيد بن عامر ، عن جويرية بن أسماء ، عن نافع ، عن ابن عمر</isnad> ، عن <source/>عمر ، قال : وافقت ربي في ثلاث : في الحجاب ، وفي أسارى بدر ، وفي مقام إبراهيم .\n",
        "      </hadith_support>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "4402|<tafsir_chunk>\n",
        "<opinions_of_scholars>\n",
        "<isnad>روي عن <source/>ابن عباس</isnad> أنهم كانوا أربعة آلاف \n",
        "        <isnad>وعنه : </isnad>كانوا ثمانية آلاف . \n",
        "        <isnad>وقال <source/>أبو صالح : </isnad>تسعة آلاف \n",
        "        <isnad>وعن <source/>ابن عباس : </isnad>أربعون ألفا \n",
        "        <isnad>وقال <source/>وهب بن منبه و<source/>أبو مالك : </isnad>كانوا بضعة وثلاثين ألفا \n",
        "      </opinions_of_scholars>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "6440|<tafsir_chunk>\n",
        "      وقد كان النبي صلى الله عليه وسلم قد أفرد في اثني عشر رجلا من أصحابه ، كما قال \n",
        "      <source/>الإمام أحمد\n",
        "      : حدثنا \n",
        "      <isnad>حسن بن موسى ، حدثنا زهير ، حدثنا أبو إسحاق أن البراء بن عازب</isnad> \n",
        "      قال : \n",
        "      <hadith_support>\n",
        "        جعل رسول الله صلى الله عليه وسلم على الرماة يوم أحد - وكانوا خمسين رجلا - \n",
        "        <isnad>عبد الله بن جبير</isnad> \n",
        "        قال : ووضعهم موضعا وقال : \n",
        '        <hadith>" إن رأيتمونا تخطفنا الطير فلا تبرحوا حتى أرسل إليكم وإن رأيتمونا ظهرنا على العدو وأوطأناهم فلا تبرحوا حتى أرسل إليكم "</hadith> \n',
        "        قال : فهزموهم . \n",
        "        \n",
        "        قال : فأنا والله رأيت النساء يشتددن على الجبل ، وقد بدت أسؤقهن وخلاخلهن رافعات ثيابهن ، فقال أصحاب عبد الله : الغنيمة ، أي قوم ، الغنيمة ، ظهر أصحابكم فما تنتظرون ؟ قال \n",
        "        <isnad>عبد الله بن جبير</isnad>\n",
        "        : أنسيتم ما قال لكم رسول الله صلى الله عليه وسلم ؟ فقالوا : إنا والله لنأتين الناس فلنصيبن من الغنيمة . فلما أتوهم صرفت وجوههم فأقبلوا منهزمين ، فذلك الذي يدعوهم الرسول في أخراكم ، فلم يبق مع رسول الله صلى الله عليه وسلم غير اثني عشر رجلا فأصابوا منا سبعين ، وكان رسول الله صلى الله عليه وسلم وأصحابه أصابوا من المشركين يوم بدر أربعين ومائة : سبعين أسيرا وسبعين قتيلا . قال أبو سفيان : أفي القوم محمد ؟ أفي القوم محمد ؟ أفي القوم محمد ؟ - ثلاثا - قال : فنهاهم رسول الله صلى الله عليه وسلم أن يجيبوه ، ثم قال : أفي القوم ابن أبي قحافة ؟ أفي القوم ابن أبي قحافة ؟ أفي القوم ابن الخطاب ؟ أفي القوم ابن الخطاب ؟ ثم أقبل على أصحابه فقال : أما هؤلاء فقد قتلوا ، قد كفيتموه . فما ملك عمر نفسه أن قال : كذبت والله يا عدو الله ، إن الذين عددت لأحياء كلهم ، وقد بقي لك ما يسوءك . فقال يوم بيوم بدر ، والحرب سجال ، إنكم ستجدون في القوم مثلة لم آمر بها ولم تسؤني ثم أخذ يرتجز ، يقول : اعل هبل . اعل هبل . فقال رسول الله صلى الله عليه وسلم : \n",
        '        <hadith>" ألا تجيبوه ؟ "</hadith> \n',
        "        قالوا : يا رسول الله ، ما نقول ؟ قال : \n",
        '        <hadith>" قولوا : الله أعلى وأجل "</hadith>\n',
        "        . قال : لنا العزى ولا عزى لكم . فقال رسول الله صلى الله عليه وسلم : \n",
        '        <hadith>" ألا تجيبوه ؟ "</hadith> \n',
        "        . قالوا : يا رسول الله ، وما نقول ؟ قال : \n",
        '        <hadith>" قولوا : الله مولانا ولا مولى لكم "</hadith>\n',
        "        .\n",
        "      </hadith_support>\n",
        "      وقد رواه \n",
        "      <source/>البخاري \n",
        "      من حديث \n",
        "      <isnad>زهير بن معاوية</isnad> \n",
        "      مختصرا ، ورواه من حديث \n",
        "      <isnad>إسرائيل ، عن أبي إسحاق</isnad> \n",
        "      بأبسط من هذا ، كما تقدم . والله أعلم .\n",
        "    </tafsir_chunk>\n",
    ],
    [
        "6456|<tafsir_chunk>\n",
        "      وقال \n",
        "      <source/>أبو داود الطيالسي\n",
        "      : حدثنا \n",
        "      <isnad>ابن المبارك ، عن إسحاق بن يحيى بن طلحة بن عبيد الله ، أخبرني عيسى بن طلحة ، عن أم المؤمنين عائشة</isnad>\n",
        "      ، رضي الله عنها ، قالت : كان \n",
        "      <isnad>أبو بكر</isnad>\n",
        "      ، رضي الله عنه ، إذا ذكر يوم أحد قال \n",
        "      <opinions_of_scholars>ذاك يوم كله لطلحة</opinions_of_scholars>\n",
        "      ، ثم أنشأ يحدث قال : \n",
        "      <historical_context>\n",
        "        كنت أول من فاء يوم أحد ، فرأيت رجلا يقاتل مع رسول الله صلى الله عليه وسلم دونه - وأراه قال : حمية فقال فقلت : كن طلحة ، حيث فاتني ما فاتني ، فقلت : يكون رجلا من قومي أحب إلي ، وبيني وبين المشركين رجل لا أعرفه ، وأنا أقرب إلى رسول الله صلى الله عليه وسلم منه ، وهو يخطف المشي خطفا لا أحفظه فإذا هو \n",
        "        <isnad>أبو عبيدة بن الجراح</isnad>\n",
        "         ، فانتهينا إلى رسول الله صلى الله عليه وسلم : وقد كسرت رباعيته وشج في وجهه ، وقد دخل في وجنته حلقتان من حلق المغفر ، قال رسول الله صلى الله عليه وسلم : \n",
        '        <hadith>" عليكما صاحبكما "</hadith> \n',
        "        . يريد طلحة ، وقد نزف ، فلم نلتفت إلى قوله ، قال : وذهبت لأن أنزع ذلك من وجهه ، فقال \n",
        "        <isnad>أبو عبيدة</isnad>\n",
        "        : أقسمت عليك بحقي لما تركتني . فتركته ، فكره أن يتناولها بيده فيؤذي النبي صلى الله عليه وسلم ، فأزم عليها بفيه فاستخرج إحدى الحلقتين ، ووقعت ثنيته مع الحلقة ، ذهبت لأصنع ما صنع ، فقال : أقسمت عليك بحقي لما تركتني ، قال : ففعل مثل ما فعل في المرة الأولى ، فوقعت ثنيته الأخرى مع الحلقة ، فكان أبو عبيدة ، رضي الله عنه ، أحسن الناس هتما ، فأصلحنا من شأن رسول الله صلى الله عليه وسلم ، ثم أتينا طلحة في بعض تلك الجفار ، فإذا به بضع وسبعون أو أقل أو أكثر من طعنة ورمية وضربة ، وإذا قد قطعت إاصبعه ، فأصلحنا من شأنه .\n",
        "      </historical_context>\n",
        "      ورواه \n",
        "      <source/>الهيثم بن كليب ، والطبراني\n",
        "       ، من حديث \n",
        "      <isnad>إسحاق بن يحيى</isnad> \n",
        "      به . وعند \n",
        "      <source/>الهيثم\n",
        "       : فقال أبو عبيدة : أنشدك يا أبا بكر إلا تركتني ؟ فأخذ أبو عبيدة السهم بفيه ، فجعل ينضنضه كراهية أن يؤذي رسول الله صلى الله عليه وسلم ، ثم استل السهم بفيه فبدرت ثنية أبي عبيدة . وذكر تمامه ، واختاره \n",
        "      <source/>الحافظ الضياء المقدسي \n",
        "      في كتابه ، وقد \n",
        "      <chain_evaluation>ضعف علي بن المديني هذا الحديث من جهة إسحاق بن يحيى هذا ، فإنه تكلم فيه يحيى بن سعيد القطان ، وأحمد ، ويحيى بن معين ، والبخاري ، وأبو زرعة ، وأبو حاتم ، ومحمد بن سعد ، والنسائي وغيرهم .</chain_evaluation>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "|<tafsir_chunk>\n",
        "<fiqh_implications>\n",
        "<argument>\n",
        "<hadith_support>\n",
        "<majority_opinions>وقد استدل جمهور العلماء على حل ميتة البحر بهذه الآية الكريمة ، وبما رواه </majority_opinions>\n",
        "<isnad>الإمام مالك بن أنس</isnad>\n",
        "<majority_opinions> ، </majority_opinions>\n",
        "<isnad>عن وهب بن كيسان</isnad>\n",
        "<majority_opinions> ، </majority_opinions>\n",
        "<isnad>عن جابر بن عبد الله</isnad>\n",
        "<majority_opinions> قال : </majority_opinions>\n",
        "<hadith>بعث رسول الله صلى الله عليه وسلم بعثا قبل الساحل ، فأمر عليهم أبا عبيدة بن الجراح ، وهم ثلاثمائة ، قال : وأنا فيهم .</hadith>\n",
        "<majority_opinions> قال : </majority_opinions>\n",
        "<hadith>فخرجنا ، حتى إذا كنا ببعض الطريق فني الزاد ، فأمر أبو عبيدة بأزواد ذلك الجيش ، فجمع ذلك كله ، فكان مزودي تمر ، قال : فكان يقوتنا كل يوم قليلا قليلا حتى فني ، فلم يكن يصيبنا إلا تمرة تمرة .</hadith>\n",
        "<majority_opinions> فقلت : </majority_opinions>\n",
        "<hadith>وما تغني تمرة؟</hadith>\n",
        "<majority_opinions> فقال : </majority_opinions>\n",
        "<hadith>فقد وجدنا فقدها حين فنيت ، قال : ثم انتهينا إلى البحر ، فإذا حوت مثل الظرب ، فأكل منه ذلك الجيش ثماني عشرة ليلة .</hadith>\n",
        "<majority_opinions> ثم أمر </majority_opinions>\n",
        "<hadith>أبو عبيدة بضلعين من أضلاعه فنصبا ، ثم أمر براحلة فرحلت ، ومرت تحتهما فلم تصبهما .</hadith>\n",
        "<majority_opinions> وهذا الحديث مخرج في </majority_opinions>\n",
        "<source/>الصحيحين\n",
        "            <majority_opinions> وله طرق عن </majority_opinions>\n",
        "<source/>جابر\n",
        "            <majority_opinions> .</majority_opinions>\n",
        "<majority_opinions> وفي </majority_opinions>\n",
        "<source/>صحيح مسلم\n",
        "            <majority_opinions> من رواية </majority_opinions>\n",
        "<isnad>أبي الزبير</isnad>\n",
        "<majority_opinions> ، </majority_opinions>\n",
        "<isnad>عن جابر</isnad>\n",
        "<majority_opinions> : </majority_opinions>\n",
        "<hadith>فإذا على ساحل البحر مثل الكثيب الضخم ، فأتيناه فإذا بدابة يقال لها : العنبر قال : قال أبو عبيدة : ميتة ، ثم قال : لا نحن رسل رسول الله صلى الله عليه وسلم وفي سبيل الله ، وقد اضطررتم فكلوا قال : فأقمنا عليه شهرا ونحن ثلاثمائة حتى سمنا .</hadith>\n",
        "<majority_opinions> ولقد رأيتنا </majority_opinions>\n",
        "<hadith>نغترف من وقب عينه بالقلال الدهن ، ونقتطع منه الفدر كالثور ، أو : كقدر الثور ، قال : ولقد أخذ منا أبو عبيدة ثلاثة عشر رجلا فأقعدهم في وقب عينه ، وأخذ ضلعا من أضلاعه فأقامها ، ثم رحل أعظم بعير معنا فمر من تحتها ، وتزودنا من لحمه وشائق .</hadith>\n",
        "<majority_opinions> فلما قدمنا المدينة أتينا رسول الله صلى الله عليه وسلم .</majority_opinions>\n",
        "<majority_opinions> فذكرنا ذلك له ، فقال : </majority_opinions>\n",
        '<hadith>" هو رزق أخرجه الله لكم ، هل معكم من لحمه شيء فتطعمونا؟ "</hadith>\n',
        "<majority_opinions> قال : </majority_opinions>\n",
        "<hadith>فأرسلنا إلى رسول الله صلى الله عليه وسلم منه فأكله .</hadith>\n",
        "<variant_interpretations>\n",
        "<opinions_of_scholars>وفي بعض روايات </opinions_of_scholars>\n",
        "<source/>مسلم\n",
        "              <opinions_of_scholars> : أنهم كانوا مع النبي صلى الله عليه وسلم حين وجدوا هذه السمكة .</opinions_of_scholars>\n",
        "<opinions_of_scholars> فقال بعضهم : هي واقعة أخرى ، وقال بعضهم : بل هي قضية واحدة ، ولكن كانوا أولا مع النبي صلى الله عليه وسلم ، ثم بعثهم سرية مع </opinions_of_scholars>\n",
        "<source/>أبي عبيدة\n",
        "              <opinions_of_scholars> ، فوجدوا هذه في سريتهم تلك مع </opinions_of_scholars>\n",
        "<source/>أبي عبيدة\n",
        "              <opinions_of_scholars> ، </opinions_of_scholars>\n",
        "</variant_interpretations>\n",
        "<conclusion>والله أعلم .</conclusion>\n",
        "</hadith_support>\n",
        "</argument>\n",
        "</fiqh_implications>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "|<tafsir_chunk>\n",
        "<hadith_support>\n",
        "<fiqh_implications>\n",
        "<argument>\n",
        "<opinions_of_scholars>وقال </opinions_of_scholars>\n",
        "<isnad>مالك</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن صفوان بن سليم</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن سعيد بن سلمة</isnad>\n",
        "<opinions_of_scholars> - من آل ابن الأزرق : أن </opinions_of_scholars>\n",
        "<isnad>المغيرة بن أبي بردة</isnad>\n",
        "<opinions_of_scholars> - وهو من بني عبد الدار - أخبره ، أنه سمع </opinions_of_scholars>\n",
        "<isnad>أبا هريرة</isnad>\n",
        "<opinions_of_scholars> يقول : </opinions_of_scholars>\n",
        "<hadith>سأل رجل رسول الله صلى الله عليه وسلم فقال : يا رسول الله ، إنا نركب البحر ، ونحمل معنا القليل من الماء ، فإن توضأنا به عطشنا ، أفنتوضأ بماء البحر؟</hadith>\n",
        "<opinions_of_scholars> فقال رسول الله صلى الله عليه وسلم : </opinions_of_scholars>\n",
        '<hadith>" هو الطهور ماؤه الحل ميتته "</hadith>\n',
        "<opinions_of_scholars> .</opinions_of_scholars>\n",
        "<opinions_of_scholars> وقد روى هذا الحديث الإمامان </opinions_of_scholars>\n",
        "<source/>الشافعي\n",
        "            <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>أحمد بن حنبل\n",
        "            <opinions_of_scholars> ، و</opinions_of_scholars>\n",
        "<source/>أهل السنن الأربعة\n",
        "            <opinions_of_scholars> ، و</opinions_of_scholars>\n",
        "<chain_evaluation>صححه </chain_evaluation>\n",
        "<source/>البخاري\n",
        "            <chain_evaluation> و</chain_evaluation>\n",
        "<source/>الترمذي\n",
        "            <chain_evaluation> و</chain_evaluation>\n",
        "<source/>ابن خزيمة\n",
        "            <chain_evaluation> و</chain_evaluation>\n",
        "<source/>ابن حبان\n",
        "            <chain_evaluation> ، وغيرهم .</chain_evaluation>\n",
        "<opinions_of_scholars> وقد روي عن جماعة من الصحابة عن النبي صلى الله عليه وسلم بنحوه .</opinions_of_scholars>\n",
        "</argument>\n",
        "</fiqh_implications>\n",
        "</hadith_support>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "|<tafsir_chunk>\n",
        "<fiqh_implications>\n",
        "<variant_interpretations>\n",
        "<argument>\n",
        "<opinions_of_scholars>وقد استثنى بعضهم الضفادع وأباح ما سواها ; </opinions_of_scholars>\n",
        "<hadith_support>\n",
        "<opinions_of_scholars>لما رواه </opinions_of_scholars>\n",
        "<source/>الإمام أحمد\n",
        "              <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>أبو داود\n",
        "              <opinions_of_scholars> و</opinions_of_scholars>\n",
        "<source/>النسائي\n",
        "              <opinions_of_scholars> من رواية </opinions_of_scholars>\n",
        "<isnad>ابن أبي ذئب</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن سعيد بن خالد</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن سعيد بن المسيب</isnad>\n",
        "<opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن عبد الرحمن بن عثمان التيمي</isnad>\n",
        "<opinions_of_scholars> أن رسول الله صلى الله عليه وسلم </opinions_of_scholars>\n",
        '<hadith>" نهى عن قتل الضفدع "</hadith>\n',
        "<opinions_of_scholars> .</opinions_of_scholars>\n",
        "</hadith_support>\n",
        "<hadith_support>\n",
        "<opinions_of_scholars>ول</opinions_of_scholars>\n",
        "<source/>لنسائي\n",
        "              <opinions_of_scholars> ، </opinions_of_scholars>\n",
        "<isnad>عن عبد الله بن عمرو</isnad>\n",
        "<opinions_of_scholars> قال : </opinions_of_scholars>\n",
        "<hadith>نهى رسول الله صلى الله عليه وسلم عن قتل الضفدع ، وقال : نقيقها تسبيح .</hadith>\n",
        "</hadith_support>\n",
        "</argument>\n",
        "</variant_interpretations>\n",
        "</fiqh_implications>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "2441|<tafsir_chunk>\n",
        "<opinions_of_scholars>\n",
        "        وقال <source/>ابن أبي حاتم : حدثنا <isnad>أبو سعيد الأشج ، حدثنا إسماعيل بن علية ، عن أبي رجاء</isnad> ، عن <source/>الحسن يعني البصري : ( <quran_verse>وإذ ابتلى إبراهيم ربه بكلمات [ فأتمهن ]</quran_verse> ) قال : ابتلاه بالكوكب فرضي عنه ، وابتلاه بالقمر فرضي عنه ، وابتلاه بالشمس فرضي عنه ، وابتلاه بالهجرة فرضي عنه ، وابتلاه بالختان فرضي عنه ، وابتلاه بابنه فرضي عنه . \n",
        "        وقال <source/>ابن جرير : حدثنا <isnad>بشر بن معاذ ، حدثنا يزيد بن زريع ، حدثنا سعيد ، عن قتادة</isnad> ، قال : كان <source/>الحسن يقول : أي والله ، ابتلاه بأمر فصبر عليه : ابتلاه بالكوكب والشمس والقمر ، فأحسن في ذلك ، وعرف أن ربه دائم لا يزول ، فوجه وجهه للذي فطر السماوات والأرض حنيفا وما كان من المشركين . ثم ابتلاه بالهجرة فخرج من بلاده وقومه حتى لحق بالشام مهاجرا إلى الله ، ثم ابتلاه بالنار قبل الهجرة فصبر على ذلك . وابتلاه الله بذبح ابنه والختان فصبر على ذلك . \n",
        "        وقال <source/>عبد الرزاق : أخبرنا <isnad>معمر ، عمن سمع الحسن</isnad> يقول في قوله : ( <quran_verse>وإذ ابتلى إبراهيم ربه بكلمات [ فأتمهن ]</quran_verse> ) قال : ابتلاه الله بذبح ولده ، وبالنار ، والكوكب والشمس ، والقمر . \n",
        "        وقال <source/>أبو جعفر بن جرير : حدثنا <isnad>ابن بشار ، حدثنا سلم بن قتيبة ، حدثنا أبو هلال</isnad> ، عن <source/>الحسن ( <quran_verse>وإذ ابتلى إبراهيم ربه بكلمات</quran_verse> ) قال : ابتلاه بالكوكب ، والشمس ، والقمر ، فوجده صابرا .\n",
        "      </opinions_of_scholars>\n",
        "</tafsir_chunk>\n",
    ],
    [
        "4769|<tafsir_chunk>\n",
        "      وقال <source/>ابن أبي حاتم :\n",
        "      <isnad>حدثنا أبي ، حدثنا أبو الوليد ، حدثنا سليمان بن كثير ، عن الزهري ، عن أبي أمامة بن سهل بن حنيف ، عن أبيه</isnad> :\n",
        "      <hadith_support>\n",
        "        أن رسول الله صلى الله عليه وسلم نهى عن لونين من التمر : <technical_definitions>الجعرور</technical_definitions> و <technical_definitions>لون الحبيق</technical_definitions> . وكان الناس يتيممون شرار ثمارهم ثم يخرجونها في الصدقة ، فنزلت : ( <quran_verse>ولا تيمموا الخبيث منه تنفقون</quran_verse> ) .\n",
        "      </hadith_support>\n",
        "      ورواه <source/>أبو داود من حديث <isnad>سفيان بن حسين ، عن الزهري</isnad> [ به ] .\n",
        "      ثم قال : أسنده <source/>أبو الوليد ، عن <isnad>سليمان بن كثير ، عن الزهري</isnad> ، ولفظه :\n",
        "      <hadith>نهى رسول الله صلى الله عليه وسلم عن الجعرور ولون الحبيق أن يؤخذا في الصدقة .</hadith>\n",
        "      وقد روى <source/>النسائي هذا الحديث من طريق <isnad>عبد الجليل بن حميد اليحصبي ، عن الزهري ، عن أبي أمامة</isnad> . ولم يقل : عن أبيه ، فذكر نحوه . وكذا رواه <source/>ابن وهب ، عن <source/>عبد الجليل .\n",
        "    </tafsir_chunk>\n",
    ],
]
import re
import numpy as np
from pprint import pprint

seq = 0
init_no_id = 11273
grouped = [[]]
path = "/home/mo/desk/apps/classify/chunks_with_most_isnad_elements.xml"
with open(path) as f:
    doc = f.readlines()
    for i, line in enumerate(doc):
        match = re.match(r"^(\d+)?\|", line)
        if match:
            if match.group(1) is not None:
                match = int(match.group(1))
            else:
                match = init_no_id
                init_no_id += 1
            seq = match
            grouped.append([line])
        else:
            try:
                grouped[seq].append(line)
            except Exception:
                pass


res_start = []
res_end = []
grouped.pop(0)

for list_inside in grouped:
    res_start.extend([[m.start() for m in re.finditer("<isnad>", list_inside[0])]])
    res_end.extend([[m.start() for m in re.finditer("</isnad>", list_inside[0])]])
# res_start = list[ list(chunk)[ indexe ] ]
# res_end   = list[ list(chunk)[ indexe ] ]

pprint(f"{res_start=}")
pprint(f"{res_end=}")
els = []
for i, el in enumerate(res_start):
    if el != []:
        arr1 = np.array(el)
        arr2 = np.array(res_end[i])
        els.extend([[arr1, arr2]])
pprint(f"{els=}")
# for i, (lx, ly) in enumerate(els):
#     print(f"{lx=}")
#     print(f"{ly=}")
#     print(f"{lx[1:], "<", ly[:-1]=}")
#     if lx[1:].any() < ly[:-1].any():
#         print(f"{lx[1:] < ly[:-1]=}")
#         print(f"{100 * "#"=}")

# print(f"{els=}")
