# Rendering / filters
ABSOLUTE_FILTERS = {
    "hadith",
    "quran_verse",
    "reason_for_revelation_variants",
    "meccan_medinan",
}
FILTER_ALIASES = {
    "hadith": "hadith",
    "koranvers": "quran_verse",
    "quran": "quran_verse",
    "quran_verse": "quran_verse",
    "reason_for_revelation_variance": "reason_for_revelation_variants",
    "reason_for_revelation_variants": "reason_for_revelation_variants",
    "mekkan_medinian": "meccan_medinan",
    "meccan_medinan": "meccan_medinan",
}
DEPENDENT_FILTERS = {
    # domain-driven defaults; extend as needed
    "hadith": ["isnad"],
    "quran_verse": ["asbab_al_nuzul"],
    "reason_for_revelation_variants": ["asbab_al_nuzul"],
    "meccan_medinan": ["chronological_order"],
}

TAG_COLORS = {
    "hadith": "#f2a007",
    "isnad": "#3a7bd5",
    "source": "#50e3c2",
    "quran_verse": "#d7263d",
    "asbab_al_nuzul": "#c2185b",
    "reason_for_revelation_variants": "#8e44ad",
    "meccan_medinan": "#795548",
    "command_and_prohibition": "#009688",
    "chain_evaluation": "#607d8b",
    "linguistic_analysis": "#2c82c9",
    "fiqh_implications": "#9c27b0",
    "theological_points": "#e67e22",
}

# ---------------- Quran metadata ----------------

SURAH_NAMES = [
    "الفاتحة",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النور",
    "الفرقان",
    "الشعراء",
    "النمل",
    "القصص",
    "العنكبوت",
    "الروم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصلت",
    "الشورى",
    "الزخرف",
    "الدخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزمل",
    "المدثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الانفطار",
    "المطففين",
    "الانشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس",
]
